language: python
python:
  - "3.8"
services:
  - docker
  - postgresql
env:
  - DATABASE_URL="postgres://postgres:postgres@127.0.0.1:5432/securemailbox"
install:
  - pip install --upgrade pip setuptools
  - pip install pipenv
  - pip install --upgrade pytest
  - pipenv install
before_script:
  - psql -c 'create database securemailbox;' -U postgres
script:
  - pytest
  - docker build -t securemailbox/api:latest .
