version: '3'
services:
  db:
    image: "postgres:latest"
    env_file:
      - env_file
    networks:
      - db_nw
  flaskapp:
    build: .
    env_file:
      - env_file
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db
  nginx:
    image: "nginx:latest"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on: 
      - flaskapp
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
