version: '3'
services:
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - db_nw
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/flaskapp_prod.conf:/etc/nginx/conf.d/default.conf
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ./letsencrypt/etc/letsencrypt/live/securemailbox.duckdns.org/fullchain.pem:/etc/letsencrypt/live/securemailbox.duckdns.org/fullchain.pem
      - ./letsencrypt/etc/letsencrypt/live/securemailbox.duckdns.org/privkey.pem:/etc/letsencrypt/live/securemailbox.duckdns.org/privkey.pem
    networks:
      - web_nw
    depends_on: 
      - flaskapp
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
